"""
Items and actions bonus and malus
"""

items_bonus = {
    'Bow':                                  50,
    'Megaton Hammer':                       50,
    'Bomb Bag':                             50,
    'Boomerang':                            30,
    'Progressive Hookshot':                 50,
    'Minuet of Forest':                     30,
    'Bolero of Fire':                       30,
    'Serenade of Water':                    20,
    'Requiem of Spirit':                    40,
    'Nocturne of Shadow':                   40,
    'Prelude of Light':                     30,
    'Zeldas Lullaby':                       50,
    'Eponas Song':                          20,
    'Sarias Song':                          20,
    'Suns Song':                            20,
    'Song of Time':                         20,
    'Song of Storms':                       30,
    'Boss Key (Forest Temple)':             15,
    'Boss Key (Fire Temple)':               20,
    'Boss Key (Water Temple)':              20,
    'Boss Key (Spirit Temple)':             15,
    'Boss Key (Shadow Temple)':             15,
    'Small Key (Forest Temple)':            10,
    'Small Key (Fire Temple)':              10,
    'Small Key (Water Temple)':             10,
    'Small Key (Spirit Temple)':            10,
    'Small Key (Shadow Temple)':            10,
    'Small Key (Gerudo Training Grounds)':  5,
    'Forest Medallion':                     500,
    'Fire Medallion':                       500,
    'Water Medallion':                      500,
    'Shadow Medallion':                     500,
    'Spirit Medallion':                     500,
    'Light Medallion':                      500,
    'Kokiri Emerald':                       30,
    'Goron Ruby':                           30,
    'Zora Sapphire':                        30,
    'Magic Meter':                          50,
    'Progressive Strength Upgrade':         50,
    'Dins Fire':                            30,
    'Fire Arrows':                          20,
    'Light Arrows':                         40,
    'Hover Boots':                          40,
    'Iron Boots':                           20,
    'Mirror Shield':                        30,
    'Hylian Shield':                        5,
    'Rutos Letter':                         20,
    'Bottle':                               10,
    'Big Poe':                              10
    }



malus = {
  "KF Kokiri Sword Chest":                                  25,
  "KF Midos Top Left Chest":                                5,
  "KF Midos Top Right Chest":                               5,
  "KF Midos Bottom Left Chest":                             5,
  "KF Midos Bottom Right Chest":                            5,
  "LW Skull Kid":                                           10,
  "LW Ocarina Memory Game":                                 20,
  "LW Target in Woods":                                     5,
  "LW Deku Scrub Near Bridge":                              20,
  "LH Underwater Item":                                     5,
  "LH Sun":                                                 25,
  "LH Freestanding PoH":                                    20,
  "LH Lab Dive":                                            15,
  "LH Child Fishing":                                       30,
  "LH Adult Fishing":                                       30,
  "GV Waterfall Freestanding PoH":                          20,
  "GV Crate Freestanding PoH":                              20,
  "GV Chest":                                               10,
  "GF Chest":                                               25,
  "GF HBA 1000 Points":                                     30,
  "GF HBA 1500 Points":                                     30,
  "Wasteland Chest":                                        15,
  "Colossus Freestanding PoH":                              10,
  "Colossus Great Fairy Reward":                            15,
  "HC Great Fairy Reward":                                  30,
  "OGC Great Fairy Reward":                                 30,
  "Market 10 Big Poes":                                     35,
  "Market Shooting Gallery Reward":                         25,
  "Market Bombchu Bowling First Prize":                     10,
  "Market Bombchu Bowling Second Prize":                    10,
  "Market Treasure Chest Game Reward":                      40,
  "Market Lost Dog":                                        10,
  "Kak Anju as Adult":                                      5,
  "Kak Anju as Child":                                      100,
  "Kak Man on Roof":                                        10,
  "Kak 10 Gold Skulltula Reward":                           60,
  "Kak 20 Gold Skulltula Reward":                           120,
  "Kak 30 Gold Skulltula Reward":                           180,
  "Kak 40 Gold Skulltula Reward":                           240,
  "Kak 50 Gold Skulltula Reward":                           300,
  "Kak Impas House Freestanding PoH":                       5,
  "Kak Windmill Freestanding PoH":                          10,
  "Kak Shooting Gallery Reward":                            25,
  "Graveyard Freestanding PoH":                             10,
  "Graveyard Dampe Gravedigging Tour":                      30,
  "Graveyard Shield Grave Chest":                           5,
  "Graveyard Heart Piece Grave Chest":                      10,
  "Graveyard Composers Grave Chest":                        10,
  "Graveyard Hookshot Chest":                               25,
  "Graveyard Dampe Race Freestanding PoH":                  25,
  "DMT Chest":                                              10,
  "DMT Freestanding PoH":                                   10,
  "DMT Biggoron":                                           35,
  "GC Maze Left Chest":                                     15,
  "GC Maze Center Chest":                                   10,
  "GC Maze Right Chest":                                    10,
  "GC Pot Freestanding PoH":                                20,
  "GC Rolling Goron as Child":                              20,
  "GC Rolling Goron as Adult":                              20,
  "GC Darunias Joy": 20,
  "DMC Wall Freestanding PoH": 15,
  "DMC Volcano Freestanding PoH": 15,
  "DMC Great Fairy Reward": 15,
  "DMT Great Fairy Reward": 40,
  "ZR Frogs Ocarina Game": 80,
  "ZR Frogs in the Rain": 25,
  "ZR Near Open Grotto Freestanding PoH": 20,
  "ZR Near Domain Freestanding PoH": 20,
  "ZD Diving Minigame": 45,
  "ZD Chest": 30,
  "ZD King Zora Thawed": 20,
  "ZF Iceberg Freestanding PoH": 10,
  "ZF Bottom Freestanding PoH": 30,
  "ZF Great Fairy Reward": 20,
  "LLR Talons Chickens": 30,
  "LLR Freestanding PoH": 30,
  "Ganons Tower Boss Key Chest": 20,
  "KF Storms Grotto Chest": 20,
  "LW Near Shortcuts Grotto Chest": 10,
  "Deku Theater Skull Mask": 100,
  "LW Deku Scrub Grotto Front": 10,
  "SFM Wolfos Grotto Chest": 15,
  "HF Open Grotto Chest": 30,
  "HF Southeast Grotto Chest": 30,
  "HF Deku Scrub Grotto": 30,
  "HF Near Market Grotto Chest": 20,
  "HF Tektite Grotto Freestanding PoH": 30,
  "Kak Open Grotto Chest": 5,
  "DMT Storms Grotto Chest": 15,
  "DMC Upper Grotto Chest": 20,
  "ZR Open Grotto Chest": 20,
  "Deku Tree Map Chest": 30,
  "Deku Tree Compass Chest": 30,
  "Deku Tree Compass Room Side Chest": 30,
  "Deku Tree Basement Chest": 30,
  "Deku Tree Slingshot Chest": 30,
  "Deku Tree Slingshot Room Side Chest": 30,
  "Deku Tree Queen Gohma Heart": 30,
  "Dodongos Cavern Map Chest": 30,
  "Dodongos Cavern Compass Chest": 30,
  "Dodongos Cavern Bomb Flower Platform Chest": 30,
  "Dodongos Cavern Bomb Bag Chest": 30,
  "Dodongos Cavern End of Bridge Chest": 30,
  "Dodongos Cavern Boss Room Chest": 30,
  "Dodongos Cavern King Dodongo Heart": 30,
  "Jabu Jabus Belly Boomerang Chest": 50,
  "Jabu Jabus Belly Map Chest": 50,
  "Jabu Jabus Belly Compass Chest": 50,
  "Jabu Jabus Belly Barinade Heart": 100,
  "Forest Temple First Room Chest": 40,
  "Forest Temple First Stalfos Chest": 40,
  "Forest Temple Raised Island Courtyard Chest": 40,
  "Forest Temple Well Chest": 40,
  "Forest Temple Map Chest": 40,
  "Forest Temple Falling Ceiling Room Chest": 40,
  "Forest Temple Eye Switch Chest": 40,
  "Forest Temple Boss Key Chest": 40,
  "Forest Temple Floormaster Chest": 40,
  "Forest Temple Bow Chest": 40,
  "Forest Temple Red Poe Chest": 40,
  "Forest Temple Blue Poe Chest": 40,
  "Forest Temple Basement Chest": 40,
  "Forest Temple Phantom Ganon Heart": 40,
  "Bottom of the Well Front Left Fake Wall Chest": 20,
  "Bottom of the Well Front Center Bombable Chest": 20,
  "Bottom of the Well Right Bottom Fake Wall Chest": 20,
  "Bottom of the Well Compass Chest": 20,
  "Bottom of the Well Center Skulltula Chest": 20,
  "Bottom of the Well Back Left Bombable Chest": 20,
  "Bottom of the Well Freestanding Key": 20,
  "Bottom of the Well Lens of Truth Chest": 20,
  "Bottom of the Well Invisible Chest": 20,
  "Bottom of the Well Underwater Front Chest": 20,
  "Bottom of the Well Underwater Left Chest": 20,
  "Bottom of the Well Map Chest": 20,
  "Bottom of the Well Fire Keese Chest": 20,
  "Bottom of the Well Like Like Chest": 20,
  "Fire Temple Near Boss Chest": 45,
  "Fire Temple Flare Dancer Chest": 45,
  "Fire Temple Boss Key Chest": 45,
  "Fire Temple Volvagia Heart": 45,
  "Fire Temple Big Lava Room Lower Open Door Chest": 45,
  "Fire Temple Big Lava Room Blocked Door Chest": 45,
  "Fire Temple Boulder Maze Lower Chest": 45,
  "Fire Temple Boulder Maze Upper Chest": 45,
  "Fire Temple Boulder Maze Side Room Chest": 45,
  "Fire Temple Boulder Maze Shortcut Chest": 45,
  "Fire Temple Scarecrow Chest": 45,
  "Fire Temple Map Chest": 45,
  "Fire Temple Compass Chest": 45,
  "Fire Temple Highest Goron Chest": 45,
  "Fire Temple Megaton Hammer Chest": 45,
  "Ice Cavern Map Chest": 65,
  "Ice Cavern Compass Chest": 65,
  "Ice Cavern Iron Boots Chest": 65,
  "Ice Cavern Freestanding PoH": 65,
  "Water Temple Morpha Heart": 50,
  "Water Temple Map Chest": 50,
  "Water Temple Compass Chest": 50,
  "Water Temple Torches Chest": 50,
  "Water Temple Central Bow Target Chest": 50,
  "Water Temple Boss Key Chest": 50,
  "Water Temple Cracked Wall Chest": 50,
  "Water Temple Dragon Chest": 50,
  "Water Temple Central Pillar Chest": 60,
  "Water Temple Longshot Chest": 60,
  "Water Temple River Chest": 60,
  "Shadow Temple Map Chest": 40,
  "Shadow Temple Hover Boots Chest": 40,
  "Shadow Temple Compass Chest": 40,
  "Shadow Temple Early Silver Rupee Chest": 40,
  "Shadow Temple Invisible Blades Visible Chest": 40,
  "Shadow Temple Invisible Blades Invisible Chest": 40,
  "Shadow Temple Falling Spikes Lower Chest": 40,
  "Shadow Temple Falling Spikes Upper Chest": 40,
  "Shadow Temple Falling Spikes Switch Chest": 40,
  "Shadow Temple Invisible Spikes Chest": 40,
  "Shadow Temple Freestanding Key": 40,
  "Shadow Temple Wind Hint Chest": 40,
  "Shadow Temple After Wind Enemy Chest": 40,
  "Shadow Temple After Wind Hidden Chest": 40,
  "Shadow Temple Spike Walls Left Chest": 40,
  "Shadow Temple Boss Key Chest": 40,
  "Shadow Temple Invisible Floormaster Chest": 40,
  "Shadow Temple Bongo Bongo Heart": 40,
  "Gerudo Training Grounds Lobby Left Chest": 10,
  "Gerudo Training Grounds Lobby Right Chest": 10,
  "Gerudo Training Grounds Stalfos Chest": 20,
  "Gerudo Training Grounds Beamos Chest": 20,
  "Gerudo Training Grounds Hidden Ceiling Chest": 10,
  "Gerudo Training Grounds Maze Path First Chest": 10,
  "Gerudo Training Grounds Maze Path Second Chest": 10,
  "Gerudo Training Grounds Maze Path Third Chest": 10,
  "Gerudo Training Grounds Maze Path Final Chest": 10,
  "Gerudo Training Grounds Maze Right Central Chest": 10,
  "Gerudo Training Grounds Maze Right Side Chest": 10,
  "Gerudo Training Grounds Freestanding Key": 10,
  "Gerudo Training Grounds Underwater Silver Rupee Chest": 80,
  "Gerudo Training Grounds Hammer Room Clear Chest": 25,
  "Gerudo Training Grounds Hammer Room Switch Chest": 25,
  "Gerudo Training Grounds Eye Statue Chest": 25,
  "Gerudo Training Grounds Near Scarecrow Chest": 25,
  "Gerudo Training Grounds Before Heavy Block Chest": 25,
  "Gerudo Training Grounds Heavy Block First Chest": 20,
  "Gerudo Training Grounds Heavy Block Second Chest": 20,
  "Gerudo Training Grounds Heavy Block Third Chest": 20,
  "Gerudo Training Grounds Heavy Block Fourth Chest": 20,
  "Spirit Temple Child Bridge Chest": 25,
  "Spirit Temple Child Early Torches Chest": 25,
  "Spirit Temple Child Climb East Chest": 25,
  "Spirit Temple Child Climb North Chest": 25,
  "Spirit Temple Compass Chest": 25,
  "Spirit Temple Early Adult Right Chest": 25,
  "Spirit Temple First Mirror Right Chest": 25,
  "Spirit Temple First Mirror Left Chest": 25,
  "Spirit Temple Map Chest": 25,
  "Spirit Temple Sun Block Room Chest": 30,
  "Spirit Temple Statue Room Hand Chest": 25,
  "Spirit Temple Statue Room Northeast Chest": 25,
  "Spirit Temple Silver Gauntlets Chest": 30,
  "Spirit Temple Mirror Shield Chest": 30,
  "Spirit Temple Near Four Armos Chest": 25,
  "Spirit Temple Hallway Left Invisible Chest": 25,
  "Spirit Temple Hallway Right Invisible Chest": 25,
  "Spirit Temple Boss Key Chest": 25,
  "Spirit Temple Topmost Chest": 20,
  "Spirit Temple Twinrova Heart": 60,
  "Ganons Castle Forest Trial Chest": 10,
  "Ganons Castle Water Trial Left Chest": 10,
  "Ganons Castle Water Trial Right Chest": 10,
  "Ganons Castle Shadow Trial Front Chest": 10,
  "Ganons Castle Shadow Trial Golden Gauntlets Chest": 15,
  "Ganons Castle Spirit Trial Crystal Switch Chest": 20,
  "Ganons Castle Spirit Trial Invisible Chest": 20,
  "Ganons Castle Light Trial First Left Chest": 5,
  "Ganons Castle Light Trial Second Left Chest": 5,
  "Ganons Castle Light Trial Third Left Chest": 5,
  "Ganons Castle Light Trial First Right Chest": 5,
  "Ganons Castle Light Trial Second Right Chest": 5,
  "Ganons Castle Light Trial Third Right Chest": 5,
  "Ganons Castle Light Trial Invisible Enemies Chest": 5,
  "Ganons Castle Light Trial Lullaby Chest": 5,
  'Deliver RL':                                             5,
  'Child Trade Sequence 1':                                 5,
  'Child Trade Sequence 2':                                 10,
  'Child Trade Sequence 3':                                 5,
  'Adult Trade Sequence 1':                                 5,
  'Adult Trade Sequence 2':                                 30,
  'Adult Trade Sequence 3':                                 30,
  'Buy Magical Beans':                                      5
}

def compute_bonus(state, item_found):
    """
    Computes the bonus associated with the item found and the current state.
    """
    if item_found in items_bonus.keys():
        if state.items[item_found]['current'] == state.items[item_found]['max']:
            return 0
        else:
            return items_bonus[item_found]
    else:
        return 0
    
    
def compute_malus(state, action):
    """
    Computes the malus associated with the action chosen and the current state.
    """
    basic_malus = 5
    if action in malus:
        return malus[action]
    return basic_malus